# Generated by Django 3.2.13 on 2022-06-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='text',
            field=models.CharField(max_length=350),
        ),
    ]
